Game-Night-2301/game-night-fe

- game-night/cypress.config.js
- game-night/cypress/e2e/spec.cy.js
- game-night/cypress/fixtures/example.json
- game-night/cypress/support/commands.js
- game-night/cypress/support/e2e.js
- game-night/package-lock.json
- game-night/package.json
- [] Bug Fix
- [] Refactor
Description: Added dependencies for Cypress and react-router-dom v5.3.3
I want feedback on... N/A
Link:
> Add Cypress dependencies and react router dom 5.3.3

- README.md
- [] Bug Fix
- [] Refactor
Description: Updated JSON contract with GraphQL requirements
I want feedback on...Just making sure this is the proper format Brian had previously looked over as well
Link:
> Update JSON contract for GraphQL

- src/Components/App/App.css
- src/Components/App/App.js
- src/Components/EventCreation/Form/Form.css
- src/Components/EventCreation/Form/Form.js
- [] Bug Fix
- [] Refactor
Description: Initial styling for the Form.
I want feedback on... Styling.
Link: ![form](https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExdWZvNXlidW96cTFkeDkyeW5sMzIzOGJjOTU0bWFuMnd5NXR0d3pyMCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/iddm3qLpC8x3djZDSm/200w.gif)
> feat: Create initial styling for form - form skeleton.

- src/queries/index.js
- [] Bug Fix
- [] Refactor
Adds our GraphQL queries to a file based on the queries defined at the mock server.
I didn't separate out the mutations here, if that's desired it should be an easy enough migration.
> Add initial GraphQL queries reference file.

- src/Components/App/App.css
- src/Components/App/App.js
- src/Components/BrowseEvent/BrowseEvent.js
- src/Components/BrowseEvent/Card/Card.css
- src/Components/BrowseEvent/Card/Card.js
- src/Components/ReusableComponents/BrowserHeader/BrowserHeader.css
- src/Components/ReusableComponents/BrowserHeader/BrowserHeader.js
- src/Components/ReusableComponents/Header/Header.css
- src/Components/ReusableComponents/Header/Header.js
- src/Components/ReusableComponents/Pills/Pills.css
- src/Components/ReusableComponents/Pills/Pills.js
- src/apiCalls/apiCalls.js
- src/index.css
- [] Bug Fix
- Adds initial styling for the events browser.
- Adds some anticipated logic to render pills based on some of the high-level info (attendees, min/max players, whether the event is hosted by the user, attended by the user, or full) and some of the styling for the pills.
- Makes some minor adjustments to the universal style properties, adding in the shared page margins and font families and tweaking the header to mirror the wireframe.
Pills are a little sloppy right now. I think I need to add something to trim the description over a certain number of characters. I haven't been able to fetch events so there's a lot of commented out anticipatory code and then the hardcoded values for the purposes of being able to see what things will look like.
- [] …
> [Feature] Event Browser, Universal Styling Tweaks, Pills/Tags

- package-lock.json
- package.json
- src/Components/App/App.js
- src/Components/Error/Error.css
- src/Components/Error/Error.js
- [] Bug Fix
- [] Refactor
Description: Added styling to Error component.
I want feedback on... Styling.
Link:
> feat: Add styling to error component

- src/Components/EventDetails/Attendees/Attendees.css
- src/Components/EventDetails/Description/Description.css
- src/Components/EventDetails/EventDetails.css
- src/Components/EventDetails/EventDetails.js
- src/Components/EventDetails/EventInfo/EventInfo.css
- [] Bug Fix
Description: Just updating some css and naming conventions
I want feedback on, this is just css, but if you see anything that could be more clean let me know
Link:
> Add some css for the event details

- node_modules/.package-lock.json
- package-lock.json
- package.json
- src/Components/App/App.js
- src/Components/BrowseEvent/BrowseEvent.js
- src/Components/BrowseEvent/Card/Card.js
- src/queries/index.js
- src/utils/cleaning.js
- [] Bug Fix
Refactors the events browser to pull down the data from the actual server, removes most of the hard-coded elements (except the TBD pills), and adds a utility file to filter, clean, and sort the events.
Cleaning functions and opportunities to clean up the code or better approaches to generating the pill tags.
> Fetch and Clean Events Data

- src/Components/EventCreation/Form/Form.js
- [] Bug Fix
Description: Very minor refactor of the form, as it didn't make it in to a previous commit. Begin adding logic for Form, added Hooks. Additionally added Date.
I want feedback on... Anything specific to the code, or how to make it cleaner.
Link:
> refac: Fix casing in Form.js

- src/Components/App/App.js
- src/Components/BrowseEvent/BrowseEvent.js
- src/Components/BrowseEvent/Card/Card.css
- src/Components/BrowseEvent/Card/Card.js
- src/Components/ReusableComponents/Pills/Pills.css
- [] Bug Fix
Fixes some of the styling and the generation of tags for the event cards generated from the server data.
This is still WIP, I'll come back and polish the CSS later, but I just wanted this to display clearly for troubleshooting/verification/testing first. Let me know if you'd like any specific changes now it's up on the site and we can go back to the designs and edit.
> Fix styling and tag generation for the imported event data.

- src/Components/App/App.js
- src/Components/BrowseEvent/BrowseEvent.js
- src/Components/BrowseEvent/Card/Card.js
- src/queries/index.js
- [] Bug Fix
- Reconfigures the event browser and the all events query to use the new data established by the backend that sorts events by distance to the logged-in user.
- Reworks the Pills tags to limit the information displayed (for now) to just the status of whether the game is full or whether the current user is either the host or attending. To do so it fetches down the new properties for the user's owned games and adds a related query.
I'm not sure! 
- …
> Event Browser Revision

- cypress/e2e/profile.cy.js
- [] Bug Fix
Description: Very minor change for CI.
I want feedback on... 
Link:
> refac: Add /profile back to the visit url.

- src/Components/App/App.js
- src/Components/BrowseEvent/BrowseEvent.js
- src/Components/Profile/Profile.css
- src/Components/Profile/Profile.js
- src/Components/Profile/UserGame/UserGame.css
- src/Components/Profile/UserGame/UserGame.js
- src/Components/ReusableComponents/BrowserHeader/BrowserHeader.css
- src/Components/ReusableComponents/BrowserHeader/BrowserHeader.js
- src/queries/index.js
- [] Bug Fix
- Reworks the CSS for the profile page slightly to more closely match the design.
- Imports users' game collections and maps them to a grid of new UserGame components.
The game collection items are a work in progress right now and I haven't switched the user profile info over from the hardcoded values either. If you have any ideas for those game collection elements let me know, but for now I'm mostly adapting the existing game cards alongside the image thumbnails as trial and error suggested that was a happy medium for both showing some of the game info from the API and displaying the images in a way that doesn't look awful given their aspect ratios and white backgrounds.
- [] All of the …
> Profile Page Polishing and Game Collection

- src/Components/App/App.js
- [] Refactor
Description: Commented out profile line 
- [] This broke nothing
- [] I have reviewed my code
Link:
> Add commented out line so vercel works for testing

- src/Components/App/App.js
- [] Bug Fix
- Modifies the handling of routes so that the welcome page is the only accessible page when the user isn't logged in and so that logged out users are rerouted to that page in the event of not being logged in.
- Fixes the issue wherein some components were attempting to access data before it had been fetched/before the user had logged in.
I'm not sure!
> Router Rework

- cypress/e2e/welcomepage.cy.js
- [] Refactor
Description: Fix a spelling error 
- [] This broke nothing
- [] I have reviewed my code
- [] I have added one or more people as "Reviewers" to review & merge
Link:
> update spelling on allEvents

- cypress/fixtures/allEvents.json
- cypress/fixtures/getUserGames.json
- src/Components/BrowseEvent/BrowseEvent.js
- [] Refactor
This just modifies the fixture files for getting the events and users' games. The structure of those objects wasn't as expected so the notation for accessing the data was being thrown off.
N/A
> Modify allEvents and getUserGames Intercept Files

- cypress/e2e/profile.cy.js
- [] Bug Fix
Description: Updated profile tests - all passing LOCALLY.
I want feedback on... We will need to update the information once the Profile data is completed.
Link:
> feat: Add updated testing and intercepts for profile.

- public/index.html
- src/Components/App/App.js
- src/Components/Error/Error.css
- [] Bug Fix
Description: Added minor error routing, changed font styling.
I want feedback on... Styling.
Link:
> feat: Add error routing, change styling.

- src/Components/App/App.js
- src/Components/EventCreation/Form/Form.js
- src/queries/index.js
- [] Bug Fix
- Reworks the form, the query, and the submission handling to emulate the server's expectations for receiving the inputs for the createEvent mutation.
- As I mentioned in the Slack, I think there's a lot that can be revised here, but I just wanted to get a version up for the time being after troubleshooting the mutation. 
- I believe that the try/catch block I'm using there can be taken out due to the nature of how Apollo handles these; frankly I was just trying different approaches to see what might work best here.
- We can also work on bringing in the actual dynamic values and making sure we're passing in the right data types as needed for the input (notably, game is an integer game's id).
- I also think another near-term priority is just adding some further controls to the …
> New Event Submission

- cypress/e2e/profilepage.cy.js
- [] Bug Fix
Description: Removed a duplicate test in profilepage E2E testing.
I want feedback on... This will hopefully fix the CI for Cypress.
Link:
> refac: Remove duplicate tests in profilepage.

- src/Components/App/App.js
- src/Components/EventCreation/Form/Form.css
- src/Components/EventCreation/Form/Form.js
- src/Components/ReusableComponents/Button/Button.css
- src/Components/ReusableComponents/Button/Button.js
- src/queries/index.js
- [] Bug Fix
- Adds validation to the open-ended fields in the form - date, startTime, endTime, description, zip - to prevent the user from entering straight up bad information.
- Disables the submit button, changes its disabled state styling, and adds a tooltip telling the user to fill out the fields if they hover over the button while it's disabled.
- Limits the max characters for the description to 500.
Let me know if there's anything missing validation wise. The Form component is kind of huge at this point.
> Form Validation and Dynamic Values

- cypress/support/commands.js
- [] Bug Fix
- Essentially we've been seeing some strange discrepancies between the Cypress testing locally (still via the vercel deployment) and through the CI. This was a suggested solution due to the in-application exceptions being thrown in the CI.
- [] I have reviewed my code
- [] I have added one or more people as "Reviewers" to review & merge
> Cypress Reconfiguration

- node_modules/.package-lock.json
- src/Components/EventCreation/Form/Form.css
- src/Components/EventCreation/Form/Form.js
- src/Components/Profile/Profile.css
- src/Components/Profile/UserGame/UserGame.css
- src/Components/ReusableComponents/Button/Button.css
- [] Bug Fix
- Adds vertical scrolling to the game collection cards and gives them maximum height properties to prevent them going crazy.
- Makes the submit button smaller to appease Overlord Adriane.
Nothing.
> Profile Page Tweaks and Submit Button Smoosh

- src/Components/App/App.js
- src/Components/BrowseEvent/BrowseEvent.js
- src/Components/EventCreation/Form/Form.js
- src/Components/EventDetails/EventDetails.js
- src/Components/Profile/Profile.js
- src/Components/ReusableComponents/Header/Header.css
- src/Components/ReusableComponents/PageLoader/PageLoader.css
- src/Components/ReusableComponents/PageLoader/PageLoader.js
- [] Bug Fix
- Replaces the current stand-in loading text with a simple spinning loading animation.
- Changes how we're handling errors for failed queries so that users are being rerouted to the Error component rather than the current text popping up on a blank page.
- Adds some margin-bottom to the Header component so that we have a standardized gap between the header and the content on each page, it was looking a little cramped.
Anything style-wise. We might want to pass arguments to error to display variable messages, but that's not a top priority.
- [] I have commented on my code, particularly in hard-to-understand …
> Loading Animation, Error Redirects, and Standardized Header Margin

- src/Components/App/App.js
- src/Components/BrowseEvent/BrowseEvent.js
- src/Components/EventCreation/Form/Form.js
- src/Components/EventDetails/EventDetails.js
- src/Components/Profile/Profile.js
- src/Components/ReusableComponents/Button/Button.css
- src/Components/ReusableComponents/Header/Header.css
- src/Components/ReusableComponents/PageLoader/PageLoader.css
- src/Components/ReusableComponents/PageLoader/PageLoader.js
- src/Components/WelcomePage/WelcomePage.css
- src/Components/WelcomePage/WelcomePage.js
- [] Bug Fix
- Small edits to the welcome page to help center and rebalance the content a little. Reduces the size of the dice image, adds some clearance above the header so it's not pushed up against the top of the page, and makes the title a little bit bigger.
- Removes the spacer element and adds margin instead.
I think it could probably be messed with a tiny bit more to make it a little more centered but I'm not going to touch that for now.
- An unrelated test for the user profile isn't passing at the moment due to being unable to find a <h5> component, I think that might …
> Minor Welcome Page Style Edits and CSS Refactoring

- src/Components/App/App.js
- src/Components/BrowseEvent/BrowseEvent.js
- src/Components/EventCreation/Form/Form.js
- src/Components/EventDetails/EventDetails.js
- src/Components/Profile/Profile.css
- src/Components/Profile/Profile.js
- src/Components/Profile/UserGame/UserGame.css
- src/Components/Profile/UserGame/UserGame.js
- src/Components/ReusableComponents/Button/Button.css
- src/Components/ReusableComponents/Header/Header.css
- src/Components/ReusableComponents/PageLoader/PageLoader.css
- src/Components/ReusableComponents/PageLoader/PageLoader.js
- src/Components/WelcomePage/WelcomePage.css
- src/Components/WelcomePage/WelcomePage.js
- [] Bug Fix
- Small edits to the profile page to fix some instances where the game collection elements were appearing a little wonky. Beefs up the size of the headers, makes their colors consistent with the event browser cards, and reworks the padding of the cards.
- Adds media queries to help the page display better for different screen sizes (see below) by removing the images and then flopping over to a column format.
Let me know if you have any ideas on those images or the cards. Not really in love with any of it.
- [] All Tests are Passing (same profile test broken - on it)
- [] My code has no …
> Profile Page Edits

- src/Components/WelcomePage/WelcomePage.css
- [] Bug Fix
- [] Refactor
Description: Add media queries and flickering to the welcome page. 
I want feedback on...If we do not like the neon light I'll change it. 
Link:
> Add media queries and flicker

- cypress/e2e/recommendations.cy.js
- cypress/fixtures/getUserRecommendations.json
- src/Components/EventCreation/Form/Form.js
Apologies for mixing up some other commits in this branch.
- Fixes the form and adds a location text field for the user to define. Now I'm thinking about it, that could probably be more specific for them to avoid confusion.
- Adds back in the success/error handling and disables the button for a short period of time after a successful post to avoid accidental multiple queries. We should also add something to clear all the inputs upon a successful submit - forgot this, sorry.
- Clears the error/success messages from view after a short period of time.
- Adds in the fixture and framework for the recommendations page tests.
How can the form be made clearer to the user and less open to bad submissions etc?
- [] No Tests have …
> Fix Form + Recommendations Testing Framework

- src/Components/EventDetails/Attendees/Attendees.css
- src/Components/EventDetails/Description/Description.css
- src/Components/EventDetails/EventDetails.css
- src/Components/EventDetails/EventDetails.js
- src/Components/EventDetails/EventInfo/EventInfo.css
- src/Components/EventDetails/EventInfo/EventInfo.js
- src/Components/ReusableComponents/Header/Header.css
- [] Bug Fix
- Adds media queries to the Game Details page so that the high-level event details (current left) and the accordion (current right) will stack and reconfigure for smaller screens as they start to get cramped together.
- Makes alignment of elements consistent with other views. Embiggens some text to take advantage of the additional space and adds grid container at page level to make relative sizing of left and right a little bit more responsive.
> Game Details Media Queries

- src/Components/EventCreation/Form/Form.js
- [] Bug Fix
- [] Refactor
Description: Added a form clearing function to the Form. Currently set to a 4 second interval.
I want feedback on... If we don't want it on the 4 second interval, it will need to be refactored.
Link:
> feat: Add clearInput to form.

- src/Components/BrowseEvent/Card/Card.css
- src/Components/EventDetails/EventInfo/EventInfo.css
- src/Components/RecommendationsPage/AIRecs/AIRecs.css
- src/Components/RecommendationsPage/AIRecs/AIRecs.js
- src/Components/RecommendationsPage/RecOutput/RecOutput.css
- src/Components/RecommendationsPage/RecOutput/RecOutput.js
- src/Components/RecommendationsPage/RecommendationsPage.js
- src/Components/ReusableComponents/BrowserHeader/BrowserHeader.css
- src/Components/ReusableComponents/Button/Button.css
- src/Components/ReusableComponents/DropDown/DropDown.css
- src/Components/ReusableComponents/Pills/Pills.css
- [] Bug Fix
Description: Req css changes for consistency and also some formatting
I want feedback on how it is looking!
Link:
> Add req css styling update and also some formatting for the req files

- src/Components/EventDetails/EventDetails.js
- [] Refactor
Prevent event details component being rendered prior to the fullQuery data coming through.
> Fix Event Details Render

- cypress/e2e/recommendations.cy.js
- src/Components/RecommendationsPage/RecOutput/RecOutput.js
- Adds additional testing for the recommendations page to confirm that the panels have the content and open and close as expected and that the results populate correctly.
- Fix the cards of the game recommendation results so that they expand as on the profile page to show the game descriptions.
- [] All Tests are Passing - vercel deployment needs to be updated with the expansion changes
> Recommendations Testing and Description Fix

- cypress/e2e/recommendations.cy.js
- cypress/fixtures/sadRecs.json
- src/Components/RecommendationsPage/RecommendationsPage.js
- [] Bug Fix
- Adds a test for the error redirect to the recommendations testing suite.
- Refactors recommendations component to incorporate redirect.
- Will not be passing on CI until after merge.
> Recommendations Page Sad Path Testing

- cypress/e2e/eventdetailpage.cy.js
- cypress/e2e/recommendations.cy.js
- cypress/fixtures/error.json
- cypress/fixtures/errorEventDetail.json
- [] Bug Fix
- [] Refactor
Description: Add new tests to the event details. 
I want feedback on...if i hit all the paths 
- [] This broke nothing
Link:
> Update event details

- cypress/e2e/eventdetailpage.cy.js
- [] Bug Fix
Description: just added one small test to the event details
I want feedback on if it looks like a bad test
- [] This broke nothing
- []x My code has no unused/commented out code
Link:
> Add a sad path test to the event-details

- cypress/e2e/eventdetailpage.cy.js
- cypress/e2e/profilepage.cy.js
- cypress/e2e/recommendations.cy.js
- cypress/e2e/welcomepage.cy.js
- cypress/fixtures/errorEventDetail.json
- cypress/fixtures/sadRecs.json
- [] Bug Fix
- [] Refactor
Description:
Link:
> Update error hadling for welcome page

- cypress/e2e/createeventpage.cy.js
- [] Bug Fix
- [] Refactor
Description: Add initial test changes for sad path on form.
I want feedback on... The process - as was discussed in a live setting.
Link:
> feat: Add beginning work for sad path for form.

- cypress/e2e/createeventpage.cy.js
- [] Bug Fix
Description: Proposed error handling for if a server is down and redirected. 
I want feedback on...We need to comment in the last two lines once we have the redirect working.
Link:
> Add future error handling

- src/Components/EventCreation/Form/Form.js
- [] Bug Fix
Description: Change syntax on form.
I want feedback on... Anything.
Link:
> refac: Refactor form syntax.

- README.md
- [] Bug Fix
Description: Added some images and rearranged some things. 
I want feedback on...If we need to add anymore images I create an imgur account to store them to make it easier to upload 
Link:
> Add updates to readme

- public/manifest.json
- [] Refactor
Description: I found a random bug with the logo stuff I deleted earlier. 
Link:
> update logo issue

- node_modules/.package-lock.json
- package-lock.json
- package.json
- src/Components/App/App.css
- src/Components/App/App.js
- src/Components/BrowseEvent/BrowseEvent.js
- src/Components/BrowseEvent/Card/Card.css
- src/Components/BrowseEvent/Card/Card.js
- src/Components/EventCreation/Form/Form.js
- src/Components/EventDetails/EventDetails.js
- src/Components/EventDetails/EventInfo/EventInfo.js
- src/Components/Profile/GameModal/GameModal.css
- src/Components/Profile/GameModal/GameModal.js
- src/Components/Profile/GameResult/GameResult.css
- src/Components/Profile/GameResult/GameResult.js
- src/Components/Profile/Profile.css
- src/Components/Profile/Profile.js
- src/Components/RecommendationsPage/RecOutput/RecOutput.css
- src/Components/RecommendationsPage/RecommendationsPage.js
- src/Components/ReusableComponents/Button/Button.css
- src/Components/ReusableComponents/Header/Header.js
- src/index.js
- src/queries/index.js
- src/redux/store.js
- src/redux/user/actions.js
- src/redux/user/reducer.js
- src/redux/user/types.js
- src/utils/cleaning.js
- [] Bug Fix
- Adds React Redux to manage the user state at a global level and consequently removes some instances where we were fetching down the user data again. 
- Tweaks the query, cleaning function, and components for the events browser to display the events' distance from the user in miles.
- Adds a button to the profile page and a modal that allows the user to search for games within the database by title and add those games to the collection. Forces through a refetch of the user data each time so that games added are immediately reflected.
I think just styling given with the demo we'll be in control of the walkthrough and there won't be any review of the codebase itself. I borrowed a lot of the classes for the modal from the form to try and stay consistent. I think maybe one …
> [Post Turing Features] Global State Management, Event Distances, and Adding Games to Collection
